### ISSUE TITLE
Canonical-form schemas prevent adding optional fields in backward-compatibility mode

### ISSUE THREAD

**Issue by sjones94549** [mycujoo/go-kafka-avro#20]
# Overview

Avro doesn't include "default" in the list of attributes relevant for canonical comparison (see [spec](https://avro.apache.org/docs/1.11.0/spec.html#Parsing+Canonical+Form+for+Schemas)):
> [STRIP] Keep only attributes that are relevant to parsing data, which are: type, name, fields, symbols, items, values, size. Strip all others (e.g., doc and aliases).

We currently use this canonical form when dealing with schema registries, leading to "default" getting lost when adding schemas, checking compatibility, etc. One problem is this prevents adding new fields to schemas in `BACKWARD` compatibility mode, though adding fields with defaults (optional fields) should be allowed in this case (see [docs](https://docs.confluent.io/platform/current/schema-registry/fundamentals/schema-evolution.html#summary)):

<img width="686" alt="Screenshot 2024-03-14 at 9 49 52 AM" src="https://github.com/mycujoo/go-kafka-avro/assets/786921/7e6a6a35-c769-4ab6-aa48-501c2dd8cc13">

Thus, schema registry servers correctly reject these new canonical schemas, as they attempt to add non-optional fields.

# Proposal

Switch from the canonical-form - [schema.String()](https://github.com/mycujoo/go-kafka-avro/blob/25282c1da7a7bb73d62dbf8f033ea9e0b886217b/cached_schema_registry.go#L96), the [canonical form](https://github.com/hamba/avro/blob/1cb8acd0ae81d79ea2e80d50456ee60689ad6895/schema.go#L143-L144) - to the full JSON representation of the schema. The actual schema registry server will do its checks on this raw JSON and let us know if the schema exists, is compatible, etc.

# Problem

Depending on compatibility mode, schemas with defaults which have already been added to registry servers in their canonical form may no longer be compatible when in their complete form. Two proposed solutions:
1. Make the full-form optional, and keep the canonical-form as a default. This prevents breaking changes, but is not intuitive, as the default case would be technically broken.
2. Bump the major version, and make full-form default, but have a canonical-form option. This keeps unbroken behavior by default, but lets problem-cases work as they do now. The option would probably require a custom `WithSchemaRegistryClient` client.

# PR
I have a draft here: https://github.com/mycujoo/go-kafka-avro/pull/19

**Comment by radev** [comment]
@sjones94549 We stopped maintaining this repo. I would suggest maintaining your own fork.
